# Generated by Django 3.0.5 on 2022-02-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220201_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='locality',
            new_name='Duration',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='Email',
        ),
    ]
